[package]
name = "hackerland-bg"
version = "0.3.0"
edition = "2021"

[dependencies]
smithay-client-toolkit = "0.16"
wayland-client = "0.29"
wayland-protocols = { version = "0.29", features = ["client", "unstable_protocols"] }

